
export var uzbekiston = {

     
         "...":[],
        
        "Andijon": [
        'Andijon shahri',     
        'Andijon tumani',
        'Asaka tumani',       
        'Baliqchi tumani',
        "Bo'z tumani",        
        'Buloqboshi tumani',
        'Izboskan tumani',    
        'Jalolquduq tumani',
        'Kuyganyor tumani',   
        'Marhamat tumani',
        "Oltinko'l tumani",   
        'Oqoltin tumani',
        'Oxunboboyev tumani', 
        'Paxtaobod tumani',
        "Poytug' tumani",     
        "Qo'rg'ontepa tumani",
        'Qorasuv tumani',     
        'Shahrixon tumani',
        "Xo'jaob tumani",     
        'Xonobod tumani'
        ],    
       
        "Buxoro": [
        'Buxoro shahri',    
        'Buxoro tumani',
        "G'ijduvon tumani", 
        'Galaosiyo',
        'Gazli',            
        'Jondor tumani',
        'Kogon shahri',     
        'Kogon tumani',
        'Olot tumani',      
        'Peshku tumani',
        "Qorako'l tumani",  
        'Qorovulbozor',
        'Romitan',          
        'Shofirkon',
        'Vobkent'
        ],
       
        "Fargona": [
        'Beshariq tumani',
        "Bog'dod tumani",
        'Buvayda tumani',
        "Dang'ara tumani",
        "Farg'ona shahri",
        "Farg'ona tumani",
        'Furqat tumani',
        'Hamza tumani',
        'Langar tumani',
        "Marg'ilon tumani",
        'Navbahor tumani',
        'Oltiariq tumani',
        "Qo'qon shahri",
        'Quva tumani',
        'Quvasoy shahri',
        'Ravon tumani',
        'Rishton tumani',
        'Shohimardon tumani',
        'Toshloq tumani',
        "Uchko'priq tumani",
        'Vodil tumani',
        "Yangi Marg'ilon tumani",
        "Yangiqo'rg'on tumani",
        'Yaypan tumani',
        'Yoz tumani'
        ],    
      
        "Jizzax": [
        'Arnasoy tumani',      
        "Aydarko'l tumani",
        'Balandchaqir tumani', 
        'Dashtobod tumani',
        "Do'stlik tumani",     
        'Forish tumani',
        "G'allaorol tumani",   
        "G'oliblar tumani",
        'Gagarin tumani',      
        'Jizzax shahri',
        'Jizzax tumani',       
        'Marjonbuloq tumani',
        "O'smat tumani",       
        'Paxtakor tumani',
        'Uchtepa tumani',      
        'Yangiqishloq tumani',
        'Zafarobod tumani',    
        'Zarbdor tumani',
        'Zomin tumani'
        ],            
       
        "Namangan": [
        'Chortoq tumani',
        'Chust tumani',
        "Jomasho'y tumani",
        'Kosonsoy tumani',
        'Namangan shahri',
        'Namangan tumani',
        'Norin tumani',
        'Pop tumani',
        "To'raqo'rg'on tumani",
        'Toshbuloq tumani',
        "Uchqo'rg'on tumani",
        'Uych tumani',
        'Xaqqulobo tumani',
        "Yangiqo'rg'on"
        ],            
     
        "Navoiy": [
        'Beshrobot tumani',
        'Karmana tumani',
        'Konimex tumani',
        'Navoiy shahri',
        'Nurota tumani',
        'Qiziltepa tumani',
        'Tomdi tumani',
        'Tomdibuloq tumani',
        'Uchquduq tumani',
        'Xatirchi tumani',
        'Yangirobot tumani',
        'Zarafshon tumani'
        ],
       
        "Qashqadaryo": [
        'Beshkent tumani',   
        'Chiroqchi tumani',
        'Dehqonobod tumani', 
        "G'uzor tumani",
        'Karashina tumani',  
        'Kasbi tumani',
        'Kitob tumani',      
        'Koson tumani',
        'Mirishkor tumani',  
        'Muborak tumani',
        "Mug'lon tumani",    
        'Nishon tumani',
        'Qamashi tumani',    
        'Qarshi tumani',
        'Shahrisabz tumani', 
        'Talimarjon tumani',
        "Yakkabog' tumani"
        ],
       
        "Samarqand": [
        "Bulung'ur tumani",     
        'Chelak tumani',
        'Darband tumani',       
        "Go'zalkent tumani",
        'Gulobod tumani',       
        'Ishtixon tumani',
        'Jomboy tumani',        
        'Juma tumani',
        "Kattaqo'rg'on shahri", 
        "Kattaqo'rg'on tumani",
        'Loish tumani',         
        'Nurobod tumani',
        'Oqtosh tumani',        
        "Past darg'on tumani",
        'Paxtachi tumani',      
        'Payshanba tumani',
        'Poyariq tumani',       
        "Qo'shrobod tumani",
        'Samarqand shahri',     
        'Samarqand tumani',
        'Tayloq tumani',        
        'Urgut tumani',
        'Ziadin tumani'
        ],
      
        "Sirdaryo": [
        'Baxt tumani',
        'Boyovut tumani',
        'Guliston shahri',
        'Guliston tumani',
        "Navro'z tumani",
        'Sardoba tumani',
        'Sayxun tumani',
        'Shirin tumani',
        'Sirdaryo tumani',
        'Terenozek tumani',
        'Xovos tumani',
        'Yangiyer tumani'
        ],
      
        "Surxondaryo": [
        'Angor tumani',       
        'Bandixon tumani',
        'Boysun tumani',      
        'Denov tumani',
        "Jarqo'rg'on tumani", 
        'Muzrobod tumani',
        'Oltinsoy tumani',    
        'Qiziriq tumani',
        'Qorlik tumani',      
        "Qumqo'rg'on tumani",
        'Sariosiyo tumani',   
        'Sariq tumani',
        "Sharg'un tumani",    
        'Sherobod tumani',
        "Sho'rchi tumani",    
        'Termiz shahri',
        'Termiz tumani',      
        'Uchqizil tumani',
        'Uzun tumani',        
        'Xalqobod tumani'
        ],
    
        "Toshkent": [
        'Angren tumani',        
        'Bekobod tumani',
        "Bo'ka tumani",         
        'Chinoz tumani',
        'Chirchiq tumani',      
        'Chorvoq tumani',
        "Do'stobod tumani",     
        'Durmen tumani',
        'Eshonguzar tumani',    
        "G'azalkent tumani",
        'Gulbahor tumani',      
        'Iskandar tumani',
        'Katta Chimyon tumani', 
        'Keles tumani',
        "Ko'ksaroy tumani",     
        'Krasnogorsk tumani',
        'Mirobod tumani',       
        'Nazarbek tumani',
        "O'rtaovul tumani",     
        'Ohangaron tumani',
        'Olmaliq tumani',       
        "Oqqo'rg'on tumani",
        'Parkent tumani',       
        'Pskent tumani',
        'Qibray tumani',        
        'Qorasuv tumani',
        'Salar tumani',        
        "So'qoq tumani",        
        'Tashmore tumani',
        "To'ytepa tumani",      
        'Toshkent tumani',
        'Turkiston tumani',    
        "Xo'jakent tumani",
        'Yangibozor tumani',    
        'Yangiobod tumani',
        "Yangiyo'l tumani",     
        'Zafar tumani',
        'Zangi tumani'
        ],
          
        "Xorazm": [
        "Bog'ot tumani",  
        'Cholish tumani',
        'Gurlan tumani',  
        'Hozarasp tumani',
        'Pitnak tumani',  
        "Qo'shko'pir tumani",
        'Qorovul tumani', 
        'Shovot tumani',
        'Urganch shahri', 
        'Xiva shahri',
        'Xonqa tumani',   
        'Yangiariq tumani'
        ],
   
        "Nukus":[
            "Amudaryo tumani",
            "Beruniy tumani",
            "Chimboy shahri",
            "Ellikqal'a tumani",
            "Kegeyli tumani",
            "Moynaq tumani",
            "Nukus shahri",
            "Qanliko'l tumani",
            "Qo'ng'irot tumani",
            "Qorao'zak tumani",
            "Shumanay tumani",
            "Taxiatosh tumani",
            "To'rtko'l tumani",
            "Xo'jayli tumani",
        ],

        "Qo'qon": [
            "Beshariq tumani",
            "Qo'qon shahri",
            "Qo'qon tumani",
             "Oltinko'l tumani",
             "Paxtaobod tumani",
              "Toshloq tumani",
             "Chust tumani",
             "Yengiyer tumani",
        ],
};



